"""initial schema

Revision ID: 9590213d7d5b
Revises: 
Create Date: 2026-06-28 23:52:44.686258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9590213d7d5b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position_points',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('latitude_micro_deg', sa.Integer(), nullable=False),
    sa.Column('longitude_micro_deg', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('g_nodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('prev_alias', sa.String(), nullable=True),
    sa.Column('base_class', sa.Enum('TerminalAsset', 'LeafTransactiveNode', 'ConnectivityNode', 'MarketMaker', 'Logical', name='base_g_node_class'), nullable=False),
    sa.Column('g_node_class', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'Active', 'Suspended', 'PermanentlyDeactivated', name='g_node_status'), nullable=False),
    sa.Column('position_point_id', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['position_point_id'], ['position_points.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_g_nodes_alias'), 'g_nodes', ['alias'], unique=True)
    op.create_table('connectivity_edges',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('from_g_node_id', sa.String(), nullable=False),
    sa.Column('to_g_node_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'Active', 'Suspended', 'PermanentlyDeactivated', name='connectivity_edge_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_g_node_id'], ['g_nodes.id'], ),
    sa.ForeignKeyConstraint(['to_g_node_id'], ['g_nodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_g_node_id', 'to_g_node_id', name='uq_connectivity_edges_from_to')
    )
    op.create_index(op.f('ix_connectivity_edges_from_g_node_id'), 'connectivity_edges', ['from_g_node_id'], unique=False)
    op.create_index(op.f('ix_connectivity_edges_to_g_node_id'), 'connectivity_edges', ['to_g_node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_connectivity_edges_to_g_node_id'), table_name='connectivity_edges')
    op.drop_index(op.f('ix_connectivity_edges_from_g_node_id'), table_name='connectivity_edges')
    op.drop_table('connectivity_edges')
    op.drop_index(op.f('ix_g_nodes_alias'), table_name='g_nodes')
    op.drop_table('g_nodes')
    op.drop_table('position_points')
    # ### end Alembic commands ###
