"""alias_assignment ledger

Revision ID: d3dbdc344109
Revises: 9590213d7d5b
Create Date: 2026-06-29 00:12:52.810641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3dbdc344109'
down_revision: Union[str, Sequence[str], None] = '9590213d7d5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alias_assignment',
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('g_node_id', sa.String(), nullable=False),
    sa.Column('first_assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['g_node_id'], ['g_nodes.id'], ),
    sa.PrimaryKeyConstraint('alias')
    )
    op.create_index(op.f('ix_alias_assignment_g_node_id'), 'alias_assignment', ['g_node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alias_assignment_g_node_id'), table_name='alias_assignment')
    op.drop_table('alias_assignment')
    # ### end Alembic commands ###
